config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, :controllers => {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :welcome, only: :index
  resources :users
  resources :profiles
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  get   '/users/:id/settings' => 'users#settings', as: :user_settings
  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], :as => :finish_signup
  match '/auth/:provider/callback', to: 'sessions#create', via: 'get'
  match '/auth/failure', to: redirect('/'), via: 'get'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates_format_of :website, with: /\A(?!http:\/\/|https:\/\/)/,
    message: ": Please exclude 'http://' or 'https://'"
  validates_uniqueness_of :website, :github, :linkedin, allow_blank: true
  validates_presence_of :desired_salary, :desired_hourly, :user_id
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true, length: { is: 2 }
  validates :zip_code, presence: true, length: { is: 5 }

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{street_address}, #{city}, #{state}, #{zip_code}."
  end

  def self.search(search)
    search ? where('framework ILIKE ?', "%#{search}%") : all
  end

  def owner?(user)
    (user == self.user) ? true : false
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show]#, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    @results    = Profile.search(params[:search])
    @map_data   = get_map_data(@results) # generates @map_data
    @frameworks = ProfileHelper.available_frameworks

    respond_to do |format|
      format.js
    end
  end

  def show
    @profile = @user.profile unless @user.profile.nil?
  end

  def new
    @profile = Profile.new
    @frameworks = ProfileHelper.available_frameworks
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
    @profile = Profile.find(params[:id])
    @frameworks = ProfileHelper.available_frameworks
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      flash[:success] = "Your profile has been updated."
      redirect_to current_user
    else
      flash[:error] = @profile.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def get_map_data(results)
    map_data = []
    results.each do |profile|
      map_data << { user_id: profile.user_id, id: profile.id,
        latitude: profile.latitude, longitude: profile.longitude,
        summary: profile.summary, framework: profile.framework,
        name: profile.user.user_tag }
    end
    map_data
  end

  def profile_params
    params.require(:profile).permit!
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
  def self.available_frameworks
    ["Rails", "Meteor", "PHP", "Unspecified"]
  end

  def profile_summary
    (@profile.summary.eql? (nil || '')) ? "Coming soon!" : @profile.summary
  end

  def profile_framework
    @profile.framework.nil? ? "Unspecified" : @profile.framework
  end

  def profile_website
    @profile.website.nil? ? "" : ( link_to @profile.website,
                                   "http://#{@profile.website}" )
  end

  def profile_github
    @profile.github.nil? ? "" : ( link_to @profile.github,
                                  "http://#{@profile.github}" )
  end

  def profile_linkedin
    @profile.linkedin.nil? ? "" : ( link_to @profile.linkedin,
                                    "http://#{@profile.linkedin}" )
  end

  def profile_desired_salary
    @profile.desired_salary.nil? ? "not specified" : @profile.desired_salary
  end

  def profile_desired_hourly
    @profile.desired_hourly.nil? ? "not specified" : @profile.desired_hourly
  end
end

app/views/profiles/_form.html.erb
<div class="profile-form">
<%= form_for @profile do |f| %>
  <% if @profile.errors.any? %>
    <div class="error-explanation">
      <h3><%= pluralize(@profile.errors.count, "error") %> prohibited
        this profile from being saved:</h3>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-horizontal">
    <div class="form-group">
      <h3>Profile information:</h3>
      <div class="row">
        <p>
          <%= f.label :summary, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
          <%= f.text_area :summary, class: "form-control" %>
          </div>
        </p>
        <p>
          <%= f.label :website, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <div class="input-group">
              <div class="input-group-addon">http://</div>
              <%= f.text_field :website, placeholder: "example.com", class: "form-control" %>
            </div>
          </div>
        </p>
        <p>
          <%= f.label :github, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <div class="input-group">
              <div class="input-group-addon">http://</div>
              <%= f.text_field :github, placeholder: "example.com", class: "form-control" %>
            </div>
          </div>
        </p>
        <p>
          <%= f.label :linkedin, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <div class="input-group">
              <div class="input-group-addon">http://</div>
              <%= f.text_field :linkedin, placeholder: "example.com", class: "form-control" %>
            </div>
          </div>
        </p>
        <p>
          <%= f.label :desired_salary, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <div class="input-group">
              <div class="input-group-addon">$</div>
              <%= f.number_field :desired_salary, in: 40..200, step: 5, class: "form-control", placeholder: "k per year" %>
              <div class="input-group-addon">k per year</div>
            </div>
            <span>*required</span>
          </div>
        </p>
        <p>
          <%= f.label :desired_hourly, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <div class="input-group">
              <div class="input-group-addon">$</div>
              <%= f.number_field :desired_hourly, in: 20..100, step: 5, class: "form-control" %>
              <div class="input-group-addon">per hour</div>
            </div>
            <span>*required</span>
          </div>
        </p>
        <p>
          <%= f.label :framework, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <div class="input-group">
              <%= f.select :framework, @frameworks, class: "form-control select" %>
            </div>
          </div>
        </p>
      </div>

      <h3>Current location:</h3>
      <div class="row">
        <p>
          <%= f.label :street_address, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <%= f.text_field :street_address, class: "form-control" %>
            <span>*required</span>
          </div>
        </p>
        <p>
          <%= f.label :city, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <%= f.text_field :city, class: "form-control" %>
            <span>*required</span>
          </div>
        </p>
        <p>
          <%= f.label :state, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <%= f.text_field :state, class: "form-control" %>
            <span>*required</span>
          </div>
        </p>
        <p>
          <%= f.label :zip_code, class: "control-label col-xs-3 col-md-2" %>
          <div class="form-input col-xs-9 col-md-10">
            <%= f.text_field :zip_code, class: "form-control" %>
            <span>*required</span>
          </div>
        </p>
      </div>
    </div>
  </div>
  <div class="action">
    <%= f.submit "Save", class: "btn btn-primary", id: "update-profile-btn" %>
  </div>
<% end %>
</div>

app/views/profiles/_show.html.erb
<div class="container" id="profile-info">
  <div class="form-horizontal">
    <div class="form-group">
      <% if @profile %>
        <div class="profile-info panel panel-defaul">
          <div class="row">
            <ul>
              <li>
                <span class="control-label col-lg-3 col-xs-4">Summary:</span>
                <div class="form-input col-lg-9 col-xs-8">
                  <div class="form-control description"><%= profile_summary %></div>
                </div>
              </li>
              <li>
                <span class="control-label col-lg-3 col-xs-4">Primary framework:</span>
                <div class="form-input col-lg-9 col-xs-8">
                  <div class="form-control description"><%= profile_framework %></div>
                </div>
              </li>
              <li>
                <span class="control-label col-lg-3 col-xs-4">Website:</span>
                <div class="form-input col-lg-9 col-xs-8">
                  <div class="form-control description"><%= profile_website %></div>
                </div>
              </li>
              <li>
                <span class="control-label col-lg-3 col-xs-4">GitHub:</span>
                <div class="form-input col-lg-9 col-xs-8">
                  <div class="form-control description"><%= profile_github %></div>
                </div>
              </li>
              <li>
                <span class="control-label col-lg-3 col-xs-4">LinkedIn:</span>
                <div class="form-input col-lg-9 col-xs-8">
                  <div class="form-control description"><%= profile_linkedin %></div>
                </div>
              </li>
              <li>
                <span class="control-label col-lg-3 col-xs-4">Desired Salary:</span>
                <div class="form-input col-lg-9 col-xs-8">
                  <div class="form-control description"><%= profile_desired_salary %></div>
                </div>
              </li>
              <li>
                <span class="control-label col-lg-3 col-xs-4">Desired Hourly:</span>
                <div class="form-input col-lg-9 col-xs-8">
                  <div class="form-control description"><%= profile_desired_hourly %></div>
                </div>
              </li>
            </ul>
          </div>
        </div>
        <p>
          <%= link_to "Edit Profile", edit_profile_path(@profile),
                      class: "btn btn-primary" if @profile.owner?(current_user) %>
          <%= link_to "Send message", new_message_path(to: @user.id),
                      class: "btn btn-primary btn-lg" unless @profile.owner?(current_user)%>
        </p>
      <% else %>
        <p><%= link_to "Create Profile", new_user_profile_path(@user) %></p>
      <% end %>
    </div>
  </div>

  <!-- Google Map -->
  <div id="map"></div>

</div>

app/views/profiles/edit.html.erb
<div class="container">
  <% if current_user.id == @profile.user_id %>
    <%= render 'form' %>
  <% else %>
    <p>
      You do not have authorized access to this page.<br>
      If you believe this to be in error, please contact administration.
    </p>
  <% end %>
</div>

app/views/profiles/index.js.erb
$(".results").html("<%= j (render "welcome/results").html_safe %>");
$(".map").html("<%= j (render "welcome/map") %>");

app/views/profiles/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>