config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, :controllers => {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :welcome, only: :index
  resources :users
  resources :profiles
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  get   '/users/:id/settings' => 'users#settings', as: :user_settings
  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], :as => :finish_signup
  match '/auth/:provider/callback', to: 'sessions#create', via: 'get'
  match '/auth/failure', to: redirect('/'), via: 'get'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox.page(params[:page]).per(10)
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox.page(params[:page]).per(10)
    else
      @conversations = @mailbox.trash.page(params[:page]).per(10)
    end

    # @conversations = @mailbox.inbox.page(params[:page]).per(10)
  end

  def show
    @receipts = @conversation.receipts_for(current_user).order(created_at: :asc)
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox = current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = "inbox"
    end
    @box = params[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    count = box_count(title, @mailbox)

    content_tag :li, link_to( "#{title.capitalize} #{count}",
                              conversations_path(box: title.downcase)), opts
  end

  def box_count(title, mailbox)
    if title.eql? 'inbox'
      "(#{mailbox.inbox.count})"
    elsif title.eql? 'sent'
      "(#{mailbox.sentbox.count})"
    elsif title.eql? 'trash'
      "(#{mailbox.trash.count})"
    else
      ""
    end
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation), class: "conversation-title" %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation),
                  class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation),
                  class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
      <% if conversation.is_unread?(current_user) %>
        <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                    class: 'btn btn-xs btn-info', method: :post %>
      <% end %>
    <% end %>
  </div>

  <p><%= render 'participants', conversation: conversation %></p>

  <p><%= conversation.last_message.body %>
    <small>
      (<span class="text-muted">
        <%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %>
      </span>)
    </small>
  </p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= gravatar_for participant %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="container">
  <h1><%= current_user.user_tag %>'s Conversations</h1>
  <br>
  <div class="panel">
  <p>
    <%= link_to "Start conversation", new_message_path,
        class: "btn btn-md btn-primary" %>

    <%= link_to "View users", users_path,
        class: "btn btn-md btn-primary" %>
  </p>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-3" id="mailbox-tabs">
      <ul class="nav nav-pills nav-stacked">
        <%= mailbox_section "inbox", @box %>
        <%= mailbox_section "sent", @box %>
        <%= mailbox_section "trash", @box %>
      </ul>
    </div>
    <div class="col-sm-9">
      <% if @box == "trash" %>
        <p>
          <%= link_to "Empty trash", empty_trash_conversations_path,
                      class: "btn btn-danger", method: :delete,
                      data: {confirm: "Are you sure?"} %>
        </p>
      <% end %>
      <ul class="list-group">
        <%= render partial: "conversation", collection: @conversations %>

      </ul>
    </div>

    <%= paginate @conversations %>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="container-fluid">
  <h1>Conversation</h1>

  <p><span class="sub-header">Chatting with</span>
    <%= render 'conversations/participants', conversation: @conversation %>
  </p>

  <div class="panel panel-default">
    <div class="panel-heading"><%= @conversation.subject %></div>

    <div class="panel-body">
      <div class="messages">
        <% @receipts.each do |receipt| %>
          <div class="media">
            <% message = receipt.message %>
            <div class="media-left">
              <%= gravatar_for message.sender, 45, message.sender.user_tag %>
            </div>

            <div class="media-body">
              <h6 class="media-heading">
                <span class="message-sender-user-tag">
                  <%= message.sender.user_tag %>
                </span>
                <span class="message-created-at">
                  <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %>
                </span>
              </h6>
              <div class="message-body">
                <span class="message-text"><%= message.body %></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= form_tag reply_conversation_path(@conversation), method: :post do %>
    <div class="form-group">
      <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
    </div>
    <%= submit_tag "Send Message", class: 'btn btn-primary' %>
  <% end %>
</div>