config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, :controllers => {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :welcome, only: :index
  resources :users
  resources :profiles
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  get   '/users/:id/settings' => 'users#settings', as: :user_settings
  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], :as => :finish_signup
  match '/auth/:provider/callback', to: 'sessions#create', via: 'get'
  match '/auth/failure', to: redirect('/'), via: 'get'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include ProfileHelper

  def index
    @profiles = Profile.all
    gon.allProfiles = Map.new.get_welcome_markers(@profiles)
    @frameworks = ProfileHelper.available_frameworks

    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_map.html.erb
<!-- Map is created with javascript; see assets/javascripts/welcome.coffee -->
<div class="container-fluid">
  <div id="map"></div>
</div>

app/views/welcome/_profiles_search_form.html.erb
<div class="container-fluid">
  <%= content_tag "div", id: "profiles-search-form", class: "form-input",
      data: {frameworks: @frameworks} do %>
    <%= form_tag profiles_path, method: "get", remote: true do %>
      <%= label_tag "" %>
      <%= text_field_tag :search, params[:search], id: "profiles-search-field",
          class: "form-control", autocomplete: true,
          placeholder: "Search by framework (i.e. 'Rails')" %>

      <%= submit_tag "Search", class: "btn btn-primary", id: "search-button",
          name: "commit" %>
    <% end %>
  <% end %>
</div>

app/views/welcome/_results.html.erb
<%= content_tag "div", id: "results", class: "container-fluid",
                       data: {results: @map_data} do %>
  <% if params[:search] && params[:search] != "" &&
        @frameworks.include?(params[:search].capitalize) %>
    <p><%= params[:search].capitalize %> devs:</p>
  <% elsif !params[:search] || params[:search] == "" %>
    <p></p>
  <% else %>
    <p>No matches found.</p>
  <% end %>
<% end %>

app/views/welcome/_sidebar.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div id="sidebar">
    <div class="panel panel-default panel-group">
      <div class="panel-body">
        <div class="panel-heading" role="tab" id="heading">
          <div class="panel-title">
            <h4>Developers by Framework</h4>
          </div>

          <% @frameworks.each_with_index do |framework, i| %>
            <h3 class="panel-title" id="framework-<%= i %>">
              <a role="button" data-toggle="collapse" data-parent="#accordion"
                href="#<%= framework %>" aria-expanded="true"
                aria-controls="<%= framework %>" class="btn btn-default">
                <%= framework %>&nbsp;<span class="caret"></span>
              </a>
            </h3>
            <div id="<%= framework %>" class="panel-collapse collapse panel-scroll"
              role="tabpanel" aria-labelledby="<%= framework %>">
              <div id="profiles-by-framework">
                <ul>
                  <% @profiles.each do |profile| %>
                    <% if profile.framework == framework %>
                      <li>
                        <p>
                          <span id="<%= "pf-uid-#{profile.user_id}" %>"></span><br>
                          <div id="<%= "user-profile-#{profile.user_id}" %>"
                            class="panel-collapse collapse in panel-scroll"
                            role="tabpanel" aria-labelledby="headingOne">
                            <%= link_to "View profile", user_path(profile.user_id),
                              id: "vp-#{profile.user_id}" %>
                          </div>
                        </p>
                      </li>
                    <% end %>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron page-header" id="logo">
  <h1>DevTracker</h1>
  <h3>Connecting companies to developers</h3>
</div>

<div class="welcome-content">
  <div class="profiles-search">
    <%= render 'profiles_search_form' %>
  </div>

  <div class="results">
    <%= render 'results' %>
  </div>

  <div class="welcome-background">
    <div class="row">
      <div class="map col-md-9 col-xs-6">
        <%= render 'map' %>
      </div>

      <div class="sidebar col-md-3 col-xs-6">
        <%= render 'sidebar' %>
      </div>
    </div>
  </div>
</div>