config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, :controllers => {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  resources :welcome, only: :index
  resources :users
  resources :profiles
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  get   '/users/:id/settings' => 'users#settings', as: :user_settings
  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], :as => :finish_signup
  match '/auth/:provider/callback', to: 'sessions#create', via: 'get'
  match '/auth/failure', to: redirect('/'), via: 'get'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top is-visible">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand navbar-center">
        <%= link_to "DevTracker", root_path %>
      </div>
    </div>
    
    <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
      <li>
        <a href="#">
          <img id="gravatar-nav"
          src="<%= gravatar_image_url(current_user.email, size: 25) %>">
          &nbsp;&nbsp;<%= current_user.user_tag %>
        </a>
      </li>
      <li class="dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle"
        data-toggle="dropdown" href="#" role="button">
          My Account
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <% if current_user.profile.nil? %>
          <li>
            <%= link_to " Create your profile!", new_profile_path,
                        class: "glyphicon glyphicon-user" %>
          </li>
        <% else %>
          <li>
            <%= link_to " View profile", user_path(current_user),
                        class: "glyphicon glyphicon-user",
                        id: "view-profile-btn" %>
          </li>
          <% end %>
          <li>
            <%= link_to " Your Conversations", conversations_path,
                        class: "glyphicon glyphicon-envelope" %>
          </li>
          <li class="divider" role="separator"></li>
          <li>
            <%= link_to " Account settings",
                        edit_user_registration_path(current_user),
                        class: "glyphicon glyphicon-cog" %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li id="log-in"><%= link_to "Log in", new_user_session_path %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevTracker</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body class="<%= controller_name %> <%= action_name %> main">

    <%= render 'layouts/nav' %>

    <% flash.each do |name, msg| %>
      <% if name == 'alert' %>
        <div class="container-fluid alert alert-danger alert-box <%= name %>">
      <% else %>
        <div class="container-fluid alert alert-success alert-box <%= name %>">
      <% end %>
          <%= msg %>
        </div>
    <% end %>
    <div class="every-page">
      <%= yield %>
    </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4" id="contact-me">
            <h5>Contact Me</h5>
            <p>Paul Brescia</p>
            <p>Github: <a href="https://github.com/Brescia717">Brescia717</a></p>
            <p>LinkedIn: <a href="https://www.linkedin.com/in/paulbresciajr">paulbresciajr</a></p>
            <p>Twitter: <a href="https://twitter.com/brescia717">@brescia717</a></p>
          </div>
          <div class="col-md-5" id="follow-me">
            <h5>Follow Me</h5>
            <p>
              <a class="fa-stack fa-lg fa-2x" href="https://github.com/Brescia717">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x"></i>
              </a>
              <a class="fa-stack fa-lg fa-2x" href="https://www.linkedin.com/in/paulbresciajr">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-linkedin fa-stack-1x"></i>
              </a>
              <a class="fa-stack fa-lg fa-2x" href="https://twitter.com/brescia717">
                <i class="fa fa-square-o fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x"></i>
              </a>
            </p>
          </div>
          <div class="col-md-3" id="legal-disclaimer">
            <!-- <h5>Legal Disclaimer</h5>
            <p>
              This application uses PayPal's test environment. Only PayPal
              test environment accounts may be used for transactions.
            </p> -->
          </div>
          <div class="col-md-12" id="copyright" >
            <hr>
            <p>
              Copyright &copy; 2016 Made by Phantom Apps. All rights reserved.
              <a href="#">Terms and conditions</a>
            </p>
          </div>
        </div>
      </div>
    </footer>

</body>
</html>